config/routes.rb
Rails.application.routes.draw do
 devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions',
  :passwords => 'users/passwords',
  :confirmations => 'users/confirmations',
  :omniauth_callbacks => 'users/omniauth_callbacks',
  :unlocks => 'users/unlocks'
}
 devise_scope :user do
  get 'sign_in', :to => 'users/sessions#new'
  delete 'sign_out', :to => 'users/sessions#destroy'
 end

 resources :user_steps, only: [:index, :show, :update]

 resources :mypages do
   member do
     get :credit
     get :credit_detail
     get :user_confirmation
     get :profile
     get :logout
   end
   collection do
     get :sign_up_top
   end
 end

  root 'items#index'

  resources :items do
    collection do
      get :sell
      get :search
      get :brand_search
    end

    member do
      get :detail
      get :item_page
      post :pay
    end
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController

  def credit
    render :layout => 'add-header&pankuzu'
  end

  def credit_detail
    render :layout => 'add-header&pankuzu'
  end

  def user_confirmation
    render :layout => 'add-header&pankuzu'
  end

  def profile
    render :layout => 'add-header&pankuzu'
  end

  def logout
    render :layout => 'add-header&pankuzu'
  end

  def sign_up_top
  end

  def show
    user = User.find(params[:id])
    @nickname = current_user.name
    render :layout => 'add-header&pankuzu'
  end

end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/credit.html.haml
- breadcrumb :credit
%main.l-container
  = render './items/side-bar'
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head 支払い方法
      .l-single-inner
        %section
          .l-single-content
            %h3.l-chapter-sub-head クレジットカード一覧
          %ul.settings-payment-list
        %section.settings-add-card
          .l-single-content
            = link_to(credit_detail_mypage_path(current_user.id), class: 'submit_button') do
              = fa_icon( 'credit-card', text: " クレジットカードを追加する", class: 'fa-fw card' )
        .settings-not-regist
          = link_to root_path do
            = fa_icon( 'angle-right', text: "支払い方法について", class: 'fa-fw', right: true)

= render './items/camera-button'
= render './items/app-banner'
= render './items/footer'

app/views/mypages/credit_detail.html.haml
- breadcrumb :credit_detail
%main.l-container
  = render './items/side-bar'
  .l-content
    %section.l-card-container
      %h2.l-chapter-head
        クレジットカード情報入力
      %form#add-card-form.l-single-inner{action: "", method: "POST", :novalidate => "novalidate"}
        .l-single-content
          .form-group
            %label.card-info カード番号
            %span.form-require 必須
            %input#payment_card_no.input-default{maxlength:"19", :placeholder => "半角数字のみ", type: "text", value: ""}/
            %ul#card-no-error-wrapper.has-error-text
            %ul.signup-card-list
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?4136293187", width: "49"}/
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?4136293187", width: "34"}/
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?4136293187", width: "30"}/
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?4136293187", width: "32"}/
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?4136293187", width: "21"}/
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?4136293187", width: "32"}/
              %li
              %img{alt: "", height: "20", src: "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?4136293187", width: "32"}/
          .form-group.signup-form-expire
            %label.card-info 有効期限
            %span.form-require 必須
            %br
          .select-wrap
            %select.select-expire.select-default
              %option{value: "01"} 01
              %option{value: "02"} 02
              %option{value: "03"} 03
              %option{value: "04"} 04
              %option{value: "05"} 05
              %option{value: "06"} 06
              %option{value: "07"} 07
              %option{value: "08"} 08
              %option{value: "09"} 09
              %option{value: "10"} 10
              %option{value: "11"} 11
          %span 月
          %br
          .select-wrap
            %select.select-expire.select-default
              %option{value: "19"} 19
              %option{value: "20"} 20
              %option{value: "21"} 21
              %option{value: "22"} 22
              %option{value: "23"} 23
              %option{value: "24"} 24
              %option{value: "25"} 25
              %option{value: "26"} 26
              %option{value: "27"} 27
              %option{value: "28"} 28
          %span 年

          .form-group
            %label.card-info セキュリティコード
            %span.form-require 必須
            %input#payment_card_security_code.input-default{placeholder: "カード背面4桁もしくは3桁の番号", type: "number", value: ""}/
            %ul#security-code-error-wrapper.has-error-text
            .signup-seqcode
              .signup-seqcode-text
                .form-hidden{onclick: "changeVisible()"}
                  %span.form-question ?
                  カード裏面の番号とは？
                #info-hidden.signup-seqcode-info
                  カードの裏面をご参照ください。
                  %br/
                  %img{alt: "", src: "//www-mercari-jp.akamaized.net/assets/img/signup/seq-card.png?4136293187", width: "240"}/

          %button.submit-button.btn-default.btn-red{type: "button"} 追加する
= render './items/camera-button'
= render './items/app-banner'
= render './items/footer'

app/views/mypages/logout.html.haml
- breadcrumb :logout
%main.l-container
  = render './items/side-bar'
  .l-content
    .l-chaoter-container
      .l-single-inner
        .l-single-content-button
          =link_to(sign_out_path, method: :delete, class:"button-red") do
            ログアウト
    .footer-sell-btn
      .footer-sell-btn__wrapper
        %div 出品
        %i.fa.fa-camera
= render './items/app-banner'
= render './items/footer'

app/views/mypages/profile.html.haml
- breadcrumb :mydata
%main.l-container
  = render './items/side-bar'
  .l-content
    %section.l-profile-container
      %h2.l-chapter-head プロフィール
      %form{action: "https://www.mercari.com/jp/mypage/profile/", method: "POST"}
        .setting-profile-icon
          %figure
            %img{height: "60", src: "//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", width: "60"}/
          %input.input-default{name: "", placeholder: "例)AYA☆セール中", type: "text", value: "akihiro"}/
        .setting-profile-content
          %textarea.textarea-default{name: "introduction", placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪"}
          %button.btn-default.btn-red{type: "submit"} 変更する

= render './items/camera-button'
= render './items/app-banner'
= render './items/footer'

app/views/mypages/show.html.haml
- breadcrumb :mypage
%main.l-container
  = render './items/side-bar'
  .l-content-mypage
    %section.mypage-user-icon
      =link_to '/' do
        %figure
          =image_tag("/mypage_icon.png", width: "60")
        %h2.bold
          =@nickname
        .mypage-number
          %div
          評価
          %span.bold 10
          出品数
          %span.bold 8
    %section.mypage-tab-container-notification-todo
      .mypage-tabs
        %input#news{checked: "checked", name: "tab_item", type: "radio"}/
        %label.tab_item{for: "news"} お知らせ
        %input#to-do{name: "tab_item", type: "radio"}/
        %label.tab_item{for: "to-do"} やることリスト
        #news_content.tab_content
          %li
            =link_to(root_path, class: 'mypage-item-link') do
              =image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", :src => "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", class: 'lazyloaded')
              .mypage-item-body
                .mypage-item-text
                  【終了間近】年末年始のお得なプレゼントキャンペーン開催中！
                .time
                  %i.fa.fa-bell
                  %span 2 日前
              %i.fa.fa-chevron-right
          %li
            =link_to(root_path, class: 'mypage-item-link') do
              =image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", :src => "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", class: 'lazyloaded')
              .mypage-item-body
                .mypage-item-text お知らせ：お得なキャンペーン始まりました！詳細はこちら
                .time
                  %i.fa.fa-bell
                  %span 3 日前
              %i.fa.fa-chevron-right
          %li
            =link_to(root_path, class: 'mypage-item-link') do
              =image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", :src => "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", class: 'lazyloaded')
              .mypage-item-body
                .mypage-item-text 【5％OFFクーポンをお持ちです！】年末年始もお得にお買い物をお楽しみください♪
                .time
                  %i.fa.fa-bell
                  %span 4 日前
              %i.fa.fa-chevron-right
          %li
            =link_to(root_path, class: 'mypage-item-link') do
              =image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", :src => "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", class: 'lazyloaded')
              .mypage-item-body
                .mypage-item-text 2018年最も取引数の多かったブランドは？メルカリのトレンドをチェック♪
                .time
                  %i.fa.fa-bell
                  %span 6 日前
              %i.fa.fa-chevron-right
          %li
            =link_to(root_path, class: 'mypage-item-link') do
              =image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", :src => "//static-mercari-jp-imgtr2.akamaized.net/images/mercari_profile.png", class: 'lazyloaded')
              .mypage-item-body
                .mypage-item-text 【あと2日】ファッションアイテムが売れたら“必ず“ポイントがもらえるキャンペーン開催中
                .time
                  %i.fa.fa-bell
                  %span 17 日前
              %i.fa.fa-chevron-right
        #to-do_content.tab_content
          .merukariicon
            =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?4136293187")
          %li.mypage-item-not-found.bold
            現在、やることリストはありません

      %li.mypage-go-list
        .mypage-go-list-link
          =link_to "一覧を見る", "/jp/mypage/purchased/"
    %section.mypage-tab-container
      %h2.mypage-tab-head 購入した商品
      %section.mypage-tab-container-notification-tread
        .mypage-tabs
          %input#treading{checked: "checked", name: "t-tab_item", type: "radio"}/
          %label.t-tab_item{for: "treading"} 取引中
          %input#treaded{name: "t-tab_item", type: "radio"}/
          %label.t-tab_item{for: "treaded"} 過去の取引
          #treading_content.tab_content
            .merukariicon
              =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?4136293187")
            %li.mypage-item-not-found.bold
              取引中の商品がありません
          #treaded_content.tab_content
            .tab-content
              %li
                =link_to(root_path, class: 'mypage-item-link') do
                  =image_tag("//static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m492100228_1.jpg?1469066046", class: 'lazyloaded')
                  .mypage-item-body
                    .mypage-item-text
                      「【SALE】ヴィダルサスーン コテ25mmマイナスイオンヘアアイロン 海外対応」を購入しました。
                      %span 取引が完了しました
                    .mypage-item-status.bold.done
                      取引完了
                  %i.icon-arrow-right
              %li
                =link_to(root_path, class: 'mypage-item-link') do
                  =image_tag("//static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m615895437_1.jpg?1476378490", class: 'lazyloaded')
                  .mypage-item-body
                    .mypage-item-text
                      「clathas財布」を購入しました。
                      %span 取引が完了しました
                    .mypage-item-status.bold.done
                      取引完了
                  %i.icon-arrow-right
              %li
                =link_to(root_path, class: 'mypage-item-link') do
                  =image_tag("//static-mercari-jp-imgtr2.akamaized.net/thumb/photos/m926884174_1.jpg?1459661149", class: 'lazyloaded')
                  .mypage-item-body
                    .mypage-item-text
                      「香水セット」 を購入しました。
                      %span 取引が完了しました
                    .mypage-item-status.bold.done
                      取引完了
                  %i.icon-arrow-right
        %li.mypage-go-list
          .mypage-go-list-link
            =link_to "一覧を見る", "/jp/mypage/purchased/"
  =render './items/camera-button'
= render './items/app-banner'
= render './items/footer'

app/views/mypages/sign_up_top.html.haml
.single-container
  = render './items/purchase_header'
  .single-container__main
    %section.single-container__main__l-single
      %h2.single-container__main__l-single__head
        新規会員登録
      .single-container__main__l-single__inner
        .single-container__main__l-single__inner__content
          =link_to "../users/sign_up", class: "btn-default btn-mail" do
            %i.far.fa-envelope
            メールアドレスで登録
          %button#facebook-login.btn-default.btn-facebook
            %i.fab.fa-facebook
            Facebookで登録
          %button#google-login.btn-default.btn-google
            %i.fab.fa-google-plus-g
            Googleで登録
  = render './items/purchase_footer'

app/views/mypages/user_confirmation.html.haml
- breadcrumb :user_confirmation
%main.l-container
  = render './items/side-bar'
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-container__head
        本人情報の登録
      %p.l-chapter-container__text
        お客様のあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。
      %form.user-confirmation-form{action: "https://www.mercari.com/jp/mypage/identification/save/", method: "POST", novalidate: ""}
        .user-confirmation-form__group
          %label お名前
          %span.user-confirmation-form__group__require 必須
          %input.user-confirmation-form__group__input-default{name: "family_name_kanji", placeholder: "例）山田", type:"text", value: ""}/
          %input.user-confirmation-form__group__input-default{name: "first_name_kanji", placeholder: "例）彩", type: "text", value: ""}/
        .user-confirmation-form__group
          %label お名前カナ
          %span.user-confirmation-form__group__require 必須
          %input.user-confirmation-form__group__input-default{name: "family_name_kana", placeholder: "例）ヤマダ", type: "text", value: ""}/
          %input.user-confirmation-form__group__input-default{name: "first_name_kana", placeholder: "例）アヤ", type: "text", value: ""}/
        .user-confirmation-form__group
          %label{for: "zip_code"} 郵便番号
          %span.user-confirmation-form__group__arbitrary 任意
          %input.user-confirmation-form__group__input-default{name: "zip_code", placeholder: "例）1234567", type: "text", value: ""}/
        .user-confirmation-form__group
          %label{for: "prefecture"} 都道府県
          %span.user-confirmation-form__group__require 必須
          .user-confirmation-form__group__select-wrap
            %select.user-confirmation-form__group__select-wrap__select-default{name: "prefecture"}
              %option 北海道
              %option 青森県
              %option 岩手県
              %option 宮城県
              %option 秋田県
              %option 山形県
              %option 福島県
              %option 東京都
              %option 神奈川県
              %option 埼玉県
              %option 千葉県
              %option 茨城県
              %option 栃木県
              %option 群馬県
              %option 山梨県
              %option 新潟県
              %option 長野県
              %option 富山県
              %option 石川県
              %option 福井県
              %option 愛知県
              %option 岐阜県
              %option 静岡県
              %option 三重県
              %option 大阪府
              %option 兵庫県
              %option 京都府
              %option 滋賀県
              %option 奈良県
              %option 和歌山県
              %option 鳥取県
              %option 島根県
              %option 岡山県
              %option 広島県
              %option 山口県
              %option 徳島県
              %option 香川県
              %option 愛媛県
              %option 高知県
              %option 福岡県
              %option 佐賀県
              %option 長崎県
              %option 熊本県
              %option 大分県
              %option 宮崎県
              %option 鹿児島県
              %option 沖縄県
            %i.fas.fa-chevron-down
        .user-confirmation-form__group
          %label{for: "city"} 市区町村
          %span.user-confirmation-form__group__require 必須
          %input.user-confirmation-form__group__input-default{name: "city", placeholder: "例）横浜市緑区", type: "text", value: ""}/
        .user-confirmation-form__group
          %label{for: "address1_label"} 番地
          %span.user-confirmation-form__group__require 必須
          %input.user-confirmation-form__group__input-default{name: "address1", placeholder: "例）青山1−1−1", type: "text", value: ""}/
        .user-confirmation-form__group
          %label{for: "address2_label"} 建物名
          %span.user-confirmation-form__group__arbitrary 任意
          %input.user-confirmation-form__group__input-default{name: "address2", placeholder: "例）柳ビル103", type: "text", value: ""}/
        .user-confirmation-form__group
          %label{for: "birthday"} 生年月日
          %span.user-confirmation-form__group__require 必須
          %br/
          .user-confirmation-form__group__birthday
            .user-confirmation-form__group__birthday__select-wrap
              %select.user-confirmation-form__group__birthday__select-wrap__default{name: "year"}
                %option{value: ""} --
                %option{value: "1900"} 1900
                %option{value: "1901"} 1901
                %option{value: "1902"} 1902
                %option{value: "1903"} 1903
                %option{value: "1904"} 1904
                %option{value: "1905"} 1905
                %option{value: "1906"} 1906
                %option{value: "1907"} 1907
                %option{value: "1908"} 1908
                %option{value: "1909"} 1909
                %option{value: "1910"} 1910
                %option{value: "1911"} 1911
                %option{value: "1912"} 1912
                %option{value: "1913"} 1913
                %option{value: "1914"} 1914
                %option{value: "1915"} 1915
                %option{value: "1916"} 1916
                %option{value: "1917"} 1917
                %option{value: "1918"} 1918
                %option{value: "1919"} 1919
                %option{value: "1920"} 1920
                %option{value: "1921"} 1921
                %option{value: "1922"} 1922
                %option{value: "1923"} 1923
                %option{value: "1924"} 1924
                %option{value: "1925"} 1925
                %option{value: "1926"} 1926
                %option{value: "1927"} 1927
                %option{value: "1928"} 1928
                %option{value: "1929"} 1929
                %option{value: "1930"} 1930
                %option{value: "1931"} 1931
                %option{value: "1932"} 1932
                %option{value: "1933"} 1933
                %option{value: "1934"} 1934
                %option{value: "1935"} 1935
                %option{value: "1936"} 1936
                %option{value: "1937"} 1937
                %option{value: "1938"} 1938
                %option{value: "1939"} 1939
                %option{value: "1940"} 1940
                %option{value: "1941"} 1941
                %option{value: "1942"} 1942
                %option{value: "1943"} 1943
                %option{value: "1944"} 1944
                %option{value: "1945"} 1945
                %option{value: "1946"} 1946
                %option{value: "1947"} 1947
                %option{value: "1948"} 1948
                %option{value: "1949"} 1949
                %option{value: "1950"} 1950
                %option{value: "1951"} 1951
                %option{value: "1952"} 1952
                %option{value: "1953"} 1953
                %option{value: "1954"} 1954
                %option{value: "1955"} 1955
                %option{value: "1956"} 1956
                %option{value: "1957"} 1957
                %option{value: "1958"} 1958
                %option{value: "1959"} 1959
                %option{value: "1960"} 1960
                %option{value: "1961"} 1961
                %option{value: "1962"} 1962
                %option{value: "1963"} 1963
                %option{value: "1964"} 1964
                %option{value: "1965"} 1965
                %option{value: "1966"} 1966
                %option{value: "1967"} 1967
                %option{value: "1968"} 1968
                %option{value: "1969"} 1969
                %option{value: "1970"} 1970
                %option{value: "1971"} 1971
                %option{value: "1972"} 1972
                %option{value: "1973"} 1973
                %option{value: "1974"} 1974
                %option{value: "1975"} 1975
                %option{value: "1976"} 1976
                %option{value: "1977"} 1977
                %option{value: "1978"} 1978
                %option{value: "1979"} 1979
                %option{value: "1980"} 1980
                %option{value: "1981"} 1981
                %option{value: "1982"} 1982
                %option{value: "1983"} 1983
                %option{value: "1984"} 1984
                %option{value: "1985"} 1985
                %option{value: "1986"} 1986
                %option{value: "1987"} 1987
                %option{value: "1988"} 1988
                %option{value: "1989"} 1989
                %option{value: "1990"} 1990
                %option{value: "1991"} 1991
                %option{value: "1992"} 1992
                %option{value: "1993"} 1993
                %option{value: "1994"} 1994
                %option{value: "1995"} 1995
                %option{value: "1996"} 1996
                %option{value: "1997"} 1997
                %option{value: "1998"} 1998
                %option{value: "1999"} 1999
                %option{value: "2000"} 2000
                %option{value: "2001"} 2001
                %option{value: "2002"} 2002
                %option{value: "2003"} 2003
                %option{value: "2004"} 2004
                %option{value: "2005"} 2005
                %option{value: "2006"} 2006
                %option{value: "2007"} 2007
                %option{value: "2008"} 2008
                %option{value: "2009"} 2009
                %option{value: "2010"} 2010
                %option{value: "2011"} 2011
                %option{value: "2012"} 2012
                %option{value: "2013"} 2013
                %option{value: "2014"} 2014
                %option{value: "2015"} 2015
                %option{value: "2016"} 2016
                %option{value: "2017"} 2017
                %option{value: "2018"} 2018
              %i.fas.fa-chevron-down
            %span 年
          .user-confirmation-form__group__birthday
            .user-confirmation-form__group__birthday__select-wrap
              %select.user-confirmation-form__group__birthday__select-wrap__default{name: "month"}
                %option{value: ""} --
                %option{value: "1"} 1
                %option{value: "2"} 2
                %option{value: "3"} 3
                %option{value: "4"} 4
                %option{value: "5"} 5
                %option{value: "6"} 6
                %option{value: "7"} 7
                %option{value: "8"} 8
                %option{value: "9"} 9
                %option{value: "10"} 10
                %option{value: "11"} 11
                %option{value: "12"} 12
              %i.fas.fa-chevron-down
            %span 月
          .user-confirmation-form__group__birthday
            .user-confirmation-form__group__birthday__select-wrap
              %select.user-confirmation-form__group__birthday__select-wrap__default{name: "day"}
                %option{value: ""} --
                %option{value: "1"} 1
                %option{value: "2"} 2
                %option{value: "3"} 3
                %option{value: "4"} 4
                %option{value: "5"} 5
                %option{value: "6"} 6
                %option{value: "7"} 7
                %option{value: "8"} 8
                %option{value: "9"} 9
                %option{value: "10"} 10
                %option{value: "11"} 11
                %option{value: "12"} 12
                %option{value: "13"} 13
                %option{value: "14"} 14
                %option{value: "15"} 15
                %option{value: "16"} 16
                %option{value: "17"} 17
                %option{value: "18"} 18
                %option{value: "19"} 19
                %option{value: "20"} 20
                %option{value: "21"} 21
                %option{value: "22"} 22
                %option{value: "23"} 23
                %option{value: "24"} 24
                %option{value: "25"} 25
                %option{value: "26"} 26
                %option{value: "27"} 27
                %option{value: "28"} 28
                %option{value: "29"} 29
                %option{value: "30"} 30
                %option{value: "31"} 31
              %i.fas.fa-chevron-down
            %span 日
          %p.form-info-text
            ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
          %input{name: "birthday", type: "hidden", value: ""}/
          .clearfix
        %button.btn-default.btn-red{type: "submit"} 登録する
        .form-group.text-right
          %p
            %a.form-group.text-right__link{href: "/jp/help_center/article/423/", target: "_blank"}
              本人情報の登録について
              %i.fas.fa-chevron-right
        %input{name: "__csrf_value", type: "hidden", value: ""}/
= render './items/app-banner'
= render './items/footer'