config/routes.rb
Rails.application.routes.draw do
 devise_for :users, :controllers => {
  :registrations => 'users/registrations',
  :sessions => 'users/sessions',
  :passwords => 'users/passwords',
  :confirmations => 'users/confirmations',
  :omniauth_callbacks => 'users/omniauth_callbacks',
  :unlocks => 'users/unlocks'
}
 devise_scope :user do
  get 'sign_in', :to => 'users/sessions#new'
  delete 'sign_out', :to => 'users/sessions#destroy'
 end

 resources :user_steps, only: [:index, :show, :update]

 resources :mypages do
   member do
     get :credit
     get :credit_detail
     get :user_confirmation
     get :profile
     get :logout
   end
   collection do
     get :sign_up_top
   end
 end

  root 'items#index'

  resources :items do
    collection do
      get :sell
      get :search
      get :brand_search
    end

    member do
      get :detail
      get :item_page
      post :pay
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :seller, class_name: "User", foreign_key: "seller_id"
  belongs_to :buyer, class_name: "User", foreign_key: "buyer_id", optional: true
  belongs_to :category

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :name, presence: true
  validates :price, presence: true
  validates :introduction, presence: true
  validates :category, presence: true
  validates :status, presence: true
  validates :shipping_charge, presence: true
  validates :shipping_days, presence: true
  validates :origin_region, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  protect_from_forgery :except => [:pay]
  before_action :set_item, only: [:item_page, :show, :edit, :update, :detail, :pay, :destroy]
  before_action :require_login, only: [:new, :create]
  before_action :confirm_user_id, only: [:edit, :destroy]

  def index
    @items = Item.includes(:images).limit(4).order("created_at DESC")
    render :layout => 'add-header'
  end

  def item_page
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      flash.now[:alert] = '商品出品に失敗しました'
      render :new
    end
  end

  def show
    render :layout => 'add-header&pankuzu'
  end

  def edit
  end

  def update
    if @item.update(update_item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def detail
  end

  def pay
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: @item.price,
      card: params['payjp-token'],
      currency: 'jpy'
    )
    @item.update( buyer_id: current_user.id )
    redirect_to action: :index
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end


  def new
    @item = Item.new
    @item.images.build
  end

  def brand_search
    @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")
     respond_to do |format|
     format.json
    end
  end

  def search
    @items = Item.where('name LIKE(?)', "%#{params[:keyword]}%")
    @keyword = params[:keyword]
    render :layout => 'add-header&pankuzu'
  end


  private

    def item_params
      params.require(:item).permit(:name, :price, :status, :size, :condition, :introduction, :shipping_charge, :shipping_days, :origin_region, :shipping_method, :category_id, :brand, :buyer_id, images_attributes: [:image]).merge(seller_id: current_user.id)
    end

    def update_item_params
      params.require(:item).permit(:name, :price, :status, :size, :condition, :introduction, :shipping_charge, :shipping_days, :origin_region, :shipping_method, :category_id, :brand, :buyer_id, images_attributes: [:image, :_destroy, :id]).merge(seller_id: current_user.id)
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def require_login
      redirect_to new_user_session_url unless user_signed_in?
    end

    def confirm_user_id
      @item.seller_id == current_user.id
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_app-banner.html.haml
.app-banner
  .app-banner__pc
    .app-banner__pc__inner
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .app-banner__pc__inner__icon
        %figure
          =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?4136293187", width: "68")
        %ul.flex
          %li
            =link_to "" do
              =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4136293187", height: "40", width: "133")
          %li
            =link_to "" do
              =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4136293187", height: "40", width: "133")
    %figure.right-phon
      =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?4136293187")

app/views/items/_footer.html.haml
%footer.global-footer
  %nav
    %ul
      %li.download-app
        =link_to "" do
          =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?4136293187", width: "35px")
          今すぐ無料ダウンロード！
      %li.footer-cell
        %h2.footer-head メルカリについて
        %ul
          %li.top
            =link_to "" do
              会社概要（運営会社）
          %li
            =link_to "" do
              プライバシーポリシー
          %li
            =link_to "" do
              メルカリ利用規約
          %li
            =link_to "" do
              メルカリ利用規約・有償ポイントに関する特約
          %li
            =link_to "" do
              あんしんスマホサポート制度に関する利用特約
          %li
            =link_to "" do
              コンプライアンスポリシー
          %li
            =link_to "" do
              個人データの安全管理に係る基本方針
          %li
            =link_to "" do
              特定商取引に関する表記
          %li
            =link_to "" do
              資金決済法に基づく表示
          %li
            =link_to "" do
              法令順守と犯罪抑止のために
          %li
            =link_to "" do
              採用情報
      %li.footer-cell
        %h2.footer-head メルカリを見る
        %ul
          %li
            =link_to "" do
              カテゴリー一覧
          %li
            =link_to "" do
              ブランド一覧
          %li
            =link_to "" do
              出品地域一覧
          %li
            =link_to "" do
              公式ブログ
          %li
            =link_to "" do
              公式Twitter
          %li
            =link_to "" do
              公式Facebook
      %li.footer-cell
        %h2.footer-head ヘルプ＆ガイド
        %ul
          %li
            =link_to "" do
              メルカリガイド
          %li
            =link_to "" do
              メルカリロゴ利用ガイドライン
          %li
            =link_to "" do
              お知らせ
          %li
            =link_to "" do
              らくらくメルカリ便とは
          %li
            =link_to "" do
              ゆうゆうメルカリ便とは
          %li
            =link_to "" do
              大型らくらくメルカリ便とは
          %li
            =link_to "" do
              車体取引ガイド
          %li
            =link_to "" do
              返品・返金ポリシー
          %li
            =link_to "" do
              メルカリあんしん・あんぜん宣言！
          %li
            =link_to "" do
              偽ブランド品撲滅への取り組み
          %li
            =link_to "" do
              メルカリボックス
      %li.footer-cell
        %h2.footer-head 国
        %ul.footer-nav-lang
          %li
            =link_to "" do
              =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/flag_us.png?4136293187", width: "22")
              United States
          %li
            =link_to "" do
              =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/flag_uk.png?4136293187", width: "22")
              United Kingdom
          %li
            =link_to "" do
              =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/flag_jp.png?4136293187", width: "22")
              日本
  .footer-logo
    =link_to "" do
      =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/logo-white.svg?4136293187", width: "124", height: "33", alt: "mercari")
  %p.footer-copyright
    %small © 2018 Mercari

app/views/items/_header.html.haml
.default-countainer
  .header
    .header__inner
      .header__inner__flex
        .header__inner__flex__left
          =link_to root_path do
            =image_tag("https://www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4136293187", size: "134x36")
        .header__inner__flex__right-form
          = form_tag('/items/search', method: :get) do
            = text_field_tag(:keyword, "", class: "input-search", placeholder: "キーワードから探す")
            = button_tag '<i class="fa fa-search"></i>'.html_safe, type: "submit",class: "btn-search"

      .header__inner__nav-box
        .header__inner__nav-box__left
          %ul.header__inner__nav-box__left__item-nav
            %li
              %h2
                =link_to "", class: "header-nav-root" do
                  カテゴリーから探す
            %li
              %h2
                =link_to "", class: "header-nav-root" do
                  ブランドから探す
        - if user_signed_in?
          .header__inner__nav-box__right
            %ul.header__inner__nav-box__right__user-nav
              %li
                .header-user-icon
                  =link_to mypage_path(current_user.id) do
                    .icon
                      =image_tag("//static-mercari-jp-imgtr2.akamaized.net/images/member_photo_noimage_thumb.png", width: "32")
                    %div マイページ
              %li
                .pc-header-nav-root
                  =link_to "" do
                    %i.fa.fa-bell
                    %span お知らせ
              %li
                .pc-header-nav-root
                  =link_to "" do
                    %i.fa.fa-check
                    %span やることリスト
        - else
          .header__inner__nav-box__right
            %ul.header__inner__nav-box__right__group
              %li.header__inner__nav-box__right__group__login
                =link_to(sign_in_path, class: "header-btn btn-red") do
                  ログイン
              %li.header__inner__nav-box__right__group__login
                =link_to(sign_up_top_mypages_path, class: "header-btn btn-blue") do
                  新規会員登録

app/views/items/_purchase_footer.html.haml
%footer.single-footer
  %nav
    %ul.clearfix
      %li
        = link_to "プライバシーポリシー", root_path
      %li
        = link_to "メルカリ利用規約", root_path
      %li
        = link_to "特定商取引に関する表記", root_path
  = link_to(root_path, class: 'single-footer__logo') do
    %img{height: "65", src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?4136293187", width: "80"}/
  %p
    %small © 2018 Mercari

app/views/items/_purchase_header.html.haml
%header.single-header
  %h1
    = link_to root_path do
      %img{src: "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?4136293187"}/

app/views/items/_search_result.html.haml
.items-box-child
  = link_to item_path(item.id) do
    .child-image
      - item.images.first(1).each do |image|
        =image_tag(image.image, class: "first-image")
    .child-content
      %h3.child-content__name
        = item.name
      .child-content__bottom
        .child-content__bottom__price
          = "¥#{item.price}"
        .child-content__bottom__likes
          %i.fa.fa-heart
            %span
              8
      .child-content__tax
        (税込)

app/views/items/_side-bar.html.haml
.l-side
  %nav.l-side__mypage-nav
    %ul.l-side__mypage-navnav__list__item
      %li
        =link_to mypage_path(current_user.id), class: "l-side__mypage-nav__list__item" do
          マイページ
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          お知らせ
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          やることリスト
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          いいね！一覧
          %i.fas.fa-chevron-right
      %li
        =link_to new_item_path, class: "l-side__mypage-nav__list__item" do
          出品する
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          ニュース一覧
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          評価一覧
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          ガイド
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__list__item" do
          お問い合わせ
          %i.fas.fa-chevron-right
    %h3.l-side__mypage-nav__head 売上・ポイント
    %ul.l-side__mypage-nav__head__list
      %li
        =link_to "", class: "l-side__mypage-nav__head__list__item" do
          売上・振込申請
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__head__list__item" do
          ポイント
          %i.fas.fa-chevron-right
    %h3.l-side__mypage-nav__head 設定
    %ul.l-side__mypage-nav__head__list
      %li
        =link_to profile_mypage_path(current_user.id), class: "l-side__mypage-nav__head__list__item" do
          プロフィール
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__head__list__item" do
          住所変更
          %i.fas.fa-chevron-right
      %li
        =link_to credit_mypage_path(current_user.id), class: "l-side__mypage-nav__head__list__item" do
          支払い方法
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__head__list__item" do
          メール/パスワード
          %i.fas.fa-chevron-right
      %li
        =link_to  user_confirmation_mypage_path(current_user.id), class: "l-side__mypage-nav__head__list__item" do
          本人情報
          %i.fas.fa-chevron-right
      %li
        =link_to "", class: "l-side__mypage-nav__head__list__item" do
          電話番号の確認
          %i.fas.fa-chevron-right
      %li
        =link_to logout_mypage_path(current_user.id), class: "l-side__mypage-nav__head__list__item" do
          ログアウト
          %i.fas.fa-chevron-right

app/views/items/_top-ForOnePerson.html.haml
%section.items-box
  -if item.buyer_id != nil
    .sell-mark
      .SOLD SOLD
  = link_to item_path(item.id) do
    .figure.items-box-photo
      - item.images.first(1).each do |image|
        =image_tag(image.image, class: "main-image")
    .items-box-body
      %h3.items-box-name.font-2
        = item.name
      .items-box-num.clearfix
        .items-box-price.font-5
          = number_to_currency(item.price, unit: "￥", precision: 0)
        .items-box-likes.font-2
          %i.fa.fa-heart
          %span
            8
      %p.items-box-tax
        (税込)

app/views/items/credit.html.haml
- breadcrumb :credit
%main.l-container
  = render 'side-bar'
  .l-content
    %section.l-chapter-container
      %h2.l-chapter-head 支払い方法
      .l-single-inner
        %section
          .l-single-content
            %h3.l-chapter-sub-head クレジットカード一覧
          %ul.settings-payment-list
        %section.settings-add-card
          .l-single-content
            = link_to(root_path, class: 'submit_button') do
              = fa_icon( 'credit-card', text: " クレジットカードを追加する", class: 'fa-fw card' )
        .settings-not-regist
          = link_to root_path do
            = fa_icon( 'angle-right', text: "支払い方法について", class: 'fa-fw', right: true)

= render 'camera-button'
= render 'app-banner'
= render 'footer'

app/views/items/edit.html.haml
= render 'purchase_header'
= form_for @item do |f|
  .sell-container
    .sell-container__head
      商品の情報を入力
    .sell-container__upload
      %h3.sell-container__upload-head
        出品画像
        %span.form-require
          必須
      .sell-container__upload--max
        最大10枚までアップロードできます
      .sell-dropbox
        = f.fields_for :images do |i|
          .dz-message
            .fallback
              = i.file_field :image, {class:'dropzone needsclick', id: "item-dropzone"}
        %pre.visible-pc
          ドラッグアンドドロップ
          またはクリックしてファイルをアップロード
    .sell-content
      .form-group
        %label
          商品名
        %span.form-require
          必須
        %br
          = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "input-default"
      .form-group
        %label
          商品の説明
        %span.form-require
          必須
        = f.text_area :introduction, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "textarea-default", rows: "5"
    .sell-content
      .sell-detail
        %h3.sell-sub-head
          商品の詳細
      .category-form-box
        .form-group
          %label
            カテゴリー
            %span.form-require
              必須
            .select-wrap
          %p
            =f.collection_select :category_id, Category.roots, :id, :name, { prompt: "------" }, {class: "select-default"}
            .select-wrap
              %p
            - Category.roots.each do |root_category|
              %template{id: "childrenCategoryOf#{ root_category.id }"}
                =f.collection_select :category_id, root_category.children, :id, :name, { prompt: "------" }, {class: "select-default midium_categories"}
            .select-wrap
              %p
            - Category.roots.each do |root_category|
              - Category.children_of(root_category).each do |midium_category|
                %template{id: "childrenCategoryOf#{ midium_category.id }"}
                  = f.collection_select :category_id, midium_category.children, :id, :name, { prompt: "------" }, {class: "select-default small-categories"}

        .form-group
          %label
            サイズ
            %span.form-require
              必須
            .select-wrap
          %p
            = f.select :size, [['---'], ['XXS以下'], ['XXS（SS)'], ['S'], ['M'], ['L'], ['XL(LL)'], ['2XL(3L)'], ['3XL(4L)'], ['4XL(5L)以上'], ['FREE SIZE']], {} ,{class: "select-default"}
          %i.icon-arrow-bottom
        .form-group
          %label
            ブランド
            %span.form-gray
              任意
            .select-wrap
            = f.text_field :brand, value: "", placeholder: "例）シャネル", class: "select-default brand_search"
            .sell-brand-suggest.form-suggest-list

        .form-group
          %label
            商品の状態
            %span.form-require
              必須
            .select-wrap
          %p
            = f.select :status, [['---'], ['新品、未使用'], ['未使用に近い'], ['目立った傷や汚れなし'], ['やや傷や汚れあり'], ['傷や汚れあり'], ['全体的に状態が悪い']], {} ,{class: "select-default"}
            %i.icon-arrow-bottom
    .sell-content.clearfix
      .question
        %h3.sell-sub-head 配送について
        %a.form-question{:href => "/jp/help_center/article/68/", target: "_blank"} ?
      .post-form-box
        .form-group
          %label
            配送料の負担
            %span.form-require
              必須
            .select-wrap
          %p
            = f.select :shipping_charge, [['---'], ['送料込み(出品者負担)'], ['着払い(購入者負担)']], {} ,{class: "select-default"}
            %i.icon-arrow-bottom
        .form-group
          %label
            配送の方法
            %span.form-require
              必須
            .select-wrap
          %p
            = f.select :shipping_method, [['---'], ['未定'], ['らくらくメルカリ便'], ['クロネコヤマト'], ['ゆうパック'], ['ゆうメール']], {} ,{class: "select-default"}
            %i.icon-arrow-bottom

        .form-group
          %label
            発送元の地域
            %span.form-require
              必須
            .select-wrap
          %p
            = f.select :origin_region, [['---'], ['北海道'], ['青森県'], ['岩手県'], ['宮城県'], ['秋田県'], ['山形県'], ['福島県'], ['茨城県'], ['栃木県'], ['群馬県'], ['埼玉県'], ['千葉県'], ['東京都'], ['神奈川県'], ['新潟県'], ['富山県'], ['石川県'], ['福井県'], ['山梨県'], ['長野県'], ['岐阜県'], ['静岡県'], ['愛知県'], ['三重県'], ['滋賀県'], ['京都府'], ['大阪府'], ['兵庫県'], ['奈良県'], ['和歌山県'], ['鳥取県'], ['島根県'], ['岡山県'], ['広島県'], ['山口県'], ['徳島県'], ['香川県'], ['愛媛県'], ['高知県'], ['福岡県'], ['佐賀県'], ['長崎県'], ['熊本県'], ['大分県'], ['宮崎県'], ['鹿児島県'], ['沖縄県'], ['未定']], {} ,{class: "select-default"}
            %i.icon-arrow-bottom
        .form-group
          %label
            発送までの日数
            %span.form-require
              必須
            .select-wrap
          %p
            = f.select :shipping_days, [['---'], ['1~2日で発送'], ['2~3日で発送'], ['4~7日で発送']], {} ,{class: "select-default"}
            %i.icon-arrow-bottom

    .sell-p-content.clearfix
      .question
        %h3.sell-sub-head 販売価格(300〜9,999,999)
        %a.form-question{href: "", target: "_blank"} ?
      .sell-form-box
        %ul.sell-price
          %li.form-group
            .price-area
              %label.l-left
                価格
                %span.form-require
                  必須
              .l-right.sell-price-input
                .pricebox
                  %yen
                    ¥
                  = f.text_field :price, placeholder: "例）300", class: "input-price",id: 'price' , style:"text-align: right;"
          %li.price-data
            .l-left
              販売手数料 (10%)
            .l-right.fee
          %li.price-data.bold
            .l-left 販売利益
            .l-right.profit
      .modal{role: "dialog", tabindex: "-1"}
        .modal-inner

    .sell-content
      .sell-btn-box
        .sell-btn-box__text
          %div
            %p
              =link_to "禁止されている出品、", "", target: "_blank"
              =link_to "行為", "", target: "_blank"
              を必ずご確認ください。
            %p
              またブランド品でシリアルナンバー等がある場合はご記載ください。
              =link_to "" , target: "_blank"
              は犯罪であり処罰される可能性があります。
            %p
              また、出品をもちまして
              =link_to "加盟店規約", ""
              に同意したことになります。
        = f.submit "編集する", {class: 'btn-sell btn-red'}
        .sell-btn-gray
          もどる
= render 'purchase_footer'

app/views/items/index.html.haml
.top-main
  #slider
    #sld_area
      #sld1.sld
        .sld1.sld__visual
          .sld1-moji
            %h2
              スマホでかんたん
              フリマアプリ
            %p
              メルカリはスマホカメラからすぐに出品できる
              %br
              購入時も安心な独自システムのアプリです
            .top-main-visual-store.clearfix
            .pull-left
              =link_to "/" do
                =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?4136293187")
            .pull-left
              =link_to "/" do
                =image_tag("//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?4136293187")
          %img{alt: "", height: "100%", src: "https://www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?4136293187", width: "500"}
      #sld2.sld
        .sld2.sld__visual
      #sld3.sld
        .sld3.sld__visual
      #sld4.sld
        .sld4.sld__visual
    #sld_nav

  %section.pickup-container
    %h2.pickup-head
      ピックアップカテゴリー
    %section.items-box-container.clearfix
      %h3.text-center
        = link_to "レディース 新着アイテム", root_path
    .items-box-content.clearfix
      = render partial: 'top-ForOnePerson', collection: @items, as: :item
    .view-all
      =link_to "すべての商品を見る", root_path
    %section.items-box-container.clearfix
      %h3.text-center
        = link_to "メンズ 新着アイテム", root_path
    .items-box-content.clearfix
      = render partial: 'top-ForOnePerson', collection: @items, as: :item
    .view-all
      =link_to "すべての商品を見る", root_path
    %section.items-box-container.clearfix
      %h3.text-center
        = link_to "ベビー・キッズ 新着アイテム", root_path
    .items-box-content.clearfix
      = render partial: 'top-ForOnePerson', collection: @items, as: :item
    .view-all
      =link_to "すべての商品を見る", root_path
    %section.items-box-container.clearfix
      %h3.text-center
        = link_to "コスメ・香水・美容 新着アイテム", root_path
    .items-box-content.clearfix
      = render partial: 'top-ForOnePerson', collection: @items, as: :item
    .view-all
      =link_to "すべての商品を見る", root_path

  %section.pickup-container
  = render "camera-button"
= render "app-banner"
= render "footer"

app/views/items/item_page.html.haml
= render 'purchase_header'

%section.item-box-container.l-single-container
  %h1.item-name
    = @item.name
  .item-main-content.clearfix
    .item-photo
      .owl-carousel
        .owl-item-inner
          - @item.images.each do |image|
            = image_tag image.image, class: "owl-lazy"
    %table.item-detail-table
      %tr
        %th 出品者
        %td
          = link_to root_path do
            = @item.seller.name
          .item-rates
            .item-rates__ratings
              = fa_icon ('smile-o'), class: 'smile-pink'
              %span 451
            .item-rates__ratings
              = fa_icon ('meh-o'), class: 'meh-orange'
              %span 7
            .item-rates__ratings
              = fa_icon ('frown-o'), class: 'frown-blue'
              %span 1
      %tr
        %th カテゴリー
        %td
          = link_to root_path do
            = @item.category.name
          = link_to root_path do
            .item-detail-table-sub-category
              = fa_icon( 'angle-right', text: " タレントグッズ", class: 'fa-fw' )
          = link_to root_path do
            .item-detail-table-sub-sub-category
              = fa_icon( 'angle-right', text: " アイドル", class: 'fa-fw' )
      %tr
        %th ブランド
        %td
      %tr
        %th 商品の状態
        %td
          = @item.status
      %tr
        %th 配送料の負担
        %td
          = @item.shipping_charge
      %tr
        %th 配送の方法
        %td
          = @item.shipping_method
      %tr
        %th 配送元地域
        %td
          = link_to root_path do
            = @item.origin_region
      %tr
        %th 発送日の目安
        %td
          = @item.shipping_days

  .item-price-box.text-center
    %span.item-price.bold
      = number_to_currency(@item.price, unit: "￥", precision: 0)
    %span.item-tax (税込)
    %span.item-shipping-fee 送料込み

.item-detail-message
  .item-btns
    = link_to "商品の編集", edit_item_path(@item), class: "item-edit-btn"
    .or-center or
    = link_to "商品を一旦停止する", item_path(@item), class: "item-gray-btn"
    %br
    = link_to "この商品を削除する", item_path(@item), class: "item-gray-btn",  method: :delete

.item-detail-message
  .message-container
    .message-content
      %p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %textarea.textarea-default{name: "body", type: "text", value: ""}
      %button.message-submit.btn-default.btn-gray{type: "submit"}
        %span コメントする

= render 'purchase_footer'

app/views/items/search.html.haml
- breadcrumb :search, @keyword
.search-container
  .search-container__l-content
    .search-container__l-content__items
      %header.search-container__l-content__items__head
        - if @items.size == 0
          = "検索結果 0件"
        - else
          = "検索結果 1 ~ #{@items.length}件"
      .search-container__l-content__items__result
        .items-box-parent
          - @items.each do |item|
            = render partial: "search_result", locals: { item: item }
  .search-container__l-side

= render 'camera-button'
= render 'app-banner'
= render 'footer'